### ISSUE TITLE
Addon initialization fails

### ISSUE THREAD

**Issue by rnorden** [Atreyyo/aDF#1]
Hi, with master the following errors occur:

Interface\AddOns\aDF\aDF.lua:65: attempt to index global 'guiOptions' ( a nil value)
Interface\AddOns\aDF\aDF.lua:233: attempt to index global 'armor' ( a nil value)

enUS client - 1.12.1 - Build 5875 Release - Sep 19 2006
Enabled Addons: Ace2, aDF

**Comment by Atreyyo** [comment]
Are you using the latest version?
I thought I fixeds that issue but looks like I didnt.

**Comment by rnorden** [comment]
Yes, I pulled the master after Ayag approached me with the problem. I tried to see if it's working out of the box but it doesn't :/

**Comment by Atreyyo** [comment]
alright, redownload, should work now.

**Comment by rnorden** [comment]
+1 works now
